<?php

namespace Apie\Cms;

use Apie\Core\Attributes\CmsIcon;
use Apie\Core\Identifiers\KebabCaseSlug;
use ReflectionClass;
use Symfony\UX\Icons\Exception\IconNotFoundException;
use Symfony\UX\Icons\IconRegistryInterface;

final class IconResolver
{
    public function __construct(
        private readonly ?IconRegistryInterface $iconRegistry = null
    ) {
    }

    /**
     * @param ReflectionClass<object>|class-string<object>|string $className
     */
    public function resolve(ReflectionClass|string $className): string
    {
        $shortName = '';
        if (is_string($className)) {
            $shortName = $className;
            if (class_exists($className)) {
                $className = new ReflectionClass($className);
            }
        }
        if ($className instanceof ReflectionClass) {
            foreach ($className->getAttributes(CmsIcon::class) as $attribute) {
                return $attribute->newInstance()->icon;
            }
            $shortName = (new ReflectionClass($className))->getShortName();
        }

        $map = [
            'account' => 'mdi:account-circle',
            'activity' => 'mdi:run',
            'address' => 'mdi:map-marker',
            'admin' => 'mdi:shield-account',
            'alert' => 'mdi:alert-circle-outline',
            'analytics' => 'mdi:chart-line',
            'api' => 'mdi:api',
            'application' => 'mdi:application',
            'approval' => 'mdi:check-decagram',
            'archive' => 'mdi:archive',
            'article' => 'mdi:file-document-outline',
            'asset' => 'mdi:briefcase',
            'attachment' => 'mdi:paperclip',
            'audit' => 'mdi:clipboard-check',
            'auth' => 'mdi:account-check',
            'authorization' => 'mdi:shield-lock',
            'automation' => 'mdi:robot',
            'avatar' => 'mdi:account-circle-outline',
            'backup' => 'mdi:backup-restore',
            'badge' => 'mdi:badge-account',
            'banner' => 'mdi:flag',
            'batch' => 'mdi:layers',
            'blog' => 'mdi:post',
            'bookmark' => 'mdi:bookmark',
            'brand' => 'mdi:tag',
            'browser' => 'mdi:web',
            'bug' => 'mdi:bug',
            'bulk' => 'mdi:folder-multiple',
            'calendar' => 'mdi:calendar-month',
            'camera' => 'mdi:camera',
            'campaign' => 'mdi:bullhorn',
            'cart' => 'mdi:cart-outline',
            'cash' => 'mdi:cash',
            'catalog' => 'mdi:bookshelf',
            'category' => 'mdi:folder',
            'certificate' => 'mdi:certificate',
            'chart' => 'mdi:chart-bar',
            'chat' => 'mdi:chat',
            'checkout' => 'mdi:cash-register',
            'claim' => 'mdi:file-document-box-check',
            'class' => 'mdi:school',
            'cleaning' => 'mdi:broom',
            'client' => 'mdi:account-multiple',
            'clipboard' => 'mdi:clipboard',
            'cloud' => 'mdi:cloud',
            'collection' => 'mdi:collection',
            'column' => 'mdi:view-column',
            'command' => 'mdi:console',
            'comment' => 'mdi:comment',
            'communication' => 'mdi:message-text',
            'community' => 'mdi:account-group',
            'company' => 'mdi:office-building',
            'compare' => 'mdi:balance-scale',
            'compliance' => 'mdi:certificate',
            'component' => 'mdi:cube-outline',
            'conference' => 'mdi:microphone',
            'configuration' => 'mdi:cog',
            'connection' => 'mdi:link-variant',
            'contact' => 'mdi:phone',
            'content' => 'mdi:file-document-box-multiple',
            'contentblock' => 'mdi:cards-outline',
            'contract' => 'mdi:handshake',
            'contractor' => 'mdi:account-hard-hat',
            'conversion' => 'mdi:swap-vertical',
            'cookie' => 'mdi:cookie',
            'copy' => 'mdi:content-copy',
            'coupon' => 'mdi:ticket-percent',
            'credentials' => 'mdi:shield-key',
            'credit' => 'mdi:credit-card-outline',
            'critical' => 'mdi:alert-circle',
            'currency' => 'mdi:currency-usd',
            'currencyexchange' => 'mdi:currency-usd-off',
            'customer' => 'mdi:account-tie',
            'customerservice' => 'mdi:headset',
            'dashboard' => 'mdi:view-dashboard',
            'database' => 'mdi:database',
            'debug' => 'mdi:bug-check',
            'delete' => 'mdi:delete',
            'delivery' => 'mdi:truck-delivery',
            'department' => 'mdi:domain',
            'description' => 'mdi:format-text',
            'design' => 'mdi:palette',
            'device' => 'mdi:tablet-cellphone',
            'dialog' => 'mdi:chat-processing',
            'directory' => 'mdi:folder-multiple',
            'discount' => 'mdi:percent',
            'display' => 'mdi:monitor',
            'document' => 'mdi:file-document',
            'documentation' => 'mdi:book-open-page-variant',
            'download' => 'mdi:download',
            'draft' => 'mdi:file-document-edit',
            'driver' => 'mdi:steering',
            'dropdown' => 'mdi:menu-down',
            'duration' => 'mdi:timer',
            'edit' => 'mdi:pencil',
            'email' => 'mdi:email',
            'emails' => 'mdi:email-settings',
            'employee' => 'mdi:account-tie',
            'engine' => 'mdi:engine',
            'environment' => 'mdi:weather-partly-cloudy',
            'equipment' => 'mdi:car-brake-abs',
            'error' => 'mdi:alert-circle',
            'exception' => 'mdi:alert-circle',
            'exchange' => 'mdi:swap-horizontal',
            'experience' => 'mdi:star-circle',
            'export' => 'mdi:export-variant',
            'extension' => 'mdi:puzzle',
            'faq' => 'mdi:help-circle',
            'feature' => 'mdi:star-circle',
            'feedback' => 'mdi:message-draw',
            'field' => 'mdi:form-textbox',
            'file' => 'mdi:file',
            'filter' => 'mdi:filter-variant',
            'finance' => 'mdi:finance',
            'firewall' => 'mdi:shield-fire',
            'fitness' => 'mdi:run-fast',
            'folder' => 'mdi:folder',
            'footer' => 'mdi:footer',
            'form' => 'mdi:form-select',
            'fund' => 'mdi:bank',
            'gallery' => 'mdi:album',
            'gateway' => 'mdi:gateway',
            'geo' => 'mdi:earth',
            'gift' => 'mdi:gift',
            'goal' => 'mdi:bullseye',
            'grade' => 'mdi:star',
            'graph' => 'mdi:chart-areaspline',
            'graphnode' => 'mdi:graph',
            'grid' => 'mdi:grid',
            'group' => 'mdi:account-group',
            'growth' => 'mdi:trending-up',
            'guide' => 'mdi:book-open-page-variant',
            'handshake' => 'mdi:handshake',
            'hardware' => 'mdi:desktop-classic',
            'header' => 'mdi:header',
            'headline' => 'mdi:format-header-1',
            'health' => 'mdi:heart-pulse',
            'help' => 'mdi:help-circle',
            'helpcenter' => 'mdi:lifebuoy',
            'hierarchy' => 'mdi:sitemap',
            'history' => 'mdi:history',
            'home' => 'mdi:home',
            'hotline' => 'mdi:phone-in-talk',
            'identity' => 'mdi:account-key',
            'illustration' => 'mdi:vector-point',
            'image' => 'mdi:image',
            'immigration' => 'mdi:passport',
            'impact' => 'mdi:lightning-bolt',
            'implementation' => 'mdi:check-decagram',
            'import' => 'mdi:import',
            'insight' => 'mdi:eye',
            'insurance' => 'mdi:shield-account',
            'integration' => 'mdi:puzzle',
            'intention' => 'mdi:target',
            'inventory' => 'mdi:warehouse',
            'invoice' => 'mdi:file-document',
            'item' => 'mdi:shape',
            'job' => 'mdi:briefcase',
            'journal' => 'mdi:book-open-variant',
            'judgement' => 'mdi:gavel',
            'key' => 'mdi:key',
            'keycard' => 'mdi:key-chain',
            'keyword' => 'mdi:tag-text',
            'label' => 'mdi:label',
            'landing' => 'mdi:rocket',
            'language' => 'mdi:translate',
            'layout' => 'mdi:view-dashboard-outline',
            'lead' => 'mdi:account-star',
            'legal' => 'mdi:gavel',
            'lesson' => 'mdi:school',
            'library' => 'mdi:library-shelves',
            'license' => 'mdi:license',
            'link' => 'mdi:link',
            'linkchain' => 'mdi:link-variant',
            'list' => 'mdi:view-list',
            'live' => 'mdi:radio-tower',
            'loader' => 'mdi:loading',
            'loan' => 'mdi:cash-plus',
            'location' => 'mdi:map-marker-radius',
            'log' => 'mdi:history',
            'login' => 'mdi:login',
            'logistics' => 'mdi:truck-fast',
            'logout' => 'mdi:logout',
            'lookup' => 'mdi:magnify-scan',
            'machine' => 'mdi:robot-industrial',
            'magnet' => 'mdi:magnet',
            'make' => 'mdi:office-building-outline',
            'mail' => 'mdi:email-open',
            'mailbox' => 'mdi:mailbox',
            'maintenance' => 'mdi:tools',
            'management' => 'mdi:briefcase-check',
            'manifest' => 'mdi:file-document-box-check',
            'map' => 'mdi:map',
            'market' => 'mdi:storefront',
            'mask' => 'mdi:face-mask',
            'media' => 'mdi:play-box-multiple',
            'meeting' => 'mdi:handshake',
            'member' => 'mdi:account-multiple-plus',
            'merchant' => 'mdi:storefront',
            'message' => 'mdi:message',
            'metadata' => 'mdi:information-outline',
            'metric' => 'mdi:thermometer-lines',
            'microservice' => 'mdi:server',
            'migration' => 'mdi:database-export',
            'milestone' => 'mdi:flag-checkered',
            'mirror' => 'mdi:mirror',
            'mobile' => 'mdi:cellphone',
            'model' => 'mdi:shape-outline',
            'moderation' => 'mdi:gavel',
            'module' => 'mdi:puzzle',
            'money' => 'mdi:cash',
            'moneytransfer' => 'mdi:bank-transfer',
            'monitor' => 'mdi:monitor',
            'monitoring' => 'mdi:eye-check',
            'network' => 'mdi:server-network',
            'networking' => 'mdi:network',
            'news' => 'mdi:newspaper',
            'note' => 'mdi:note-text',
            'notification' => 'mdi:bell',
            'notificationcenter' => 'mdi:bell-ring',
            'number' => 'mdi:counter',
            'nutrition' => 'mdi:food-apple',
            'offer' => 'mdi:tag-heart',
            'office' => 'mdi:office-building',
            'operation' => 'mdi:cogs',
            'option' => 'mdi:checkbox-blank-outline',
            'order' => 'mdi:cart',
            'organization' => 'mdi:office-building',
            'overview' => 'mdi:eye',
            'owner' => 'mdi:account-star-outline',
            'page' => 'mdi:file-document-box',
            'pagebuilder' => 'mdi:page-layout-sidebar-right',
            'paint' => 'mdi:paint',
            'panel' => 'mdi:monitor-dashboard',
            'parameter' => 'mdi:tune',
            'partner' => 'mdi:handshake-outline',
            'password' => 'mdi:lock',
            'passwordreset' => 'mdi:lock-reset',
            'patch' => 'mdi:hammer-wrench',
            'payment' => 'mdi:credit-card',
            'paymentmethod' => 'mdi:credit-card-outline',
            'performance' => 'mdi:speedometer',
            'permission' => 'mdi:shield-key',
            'permissiongroup' => 'mdi:shield-account',
            'personal' => 'mdi:account',
            'phone' => 'mdi:phone-classic',
            'photo' => 'mdi:camera-outline',
            'photogallery' => 'mdi:photo',
            'phrase' => 'mdi:format-quote-open',
            'pipeline' => 'mdi:pipe',
            'plan' => 'mdi:calendar-check',
            'platform' => 'mdi:web',
            'policy' => 'mdi:file-chart',
            'popup' => 'mdi:window-maximize',
            'portal' => 'mdi:earth',
            'portfolio' => 'mdi:briefcase-account',
            'post' => 'mdi:post-outline',
            'power' => 'mdi:power',
            'preference' => 'mdi:sliders-horizontal',
            'preview' => 'mdi:eye-outline',
            'price' => 'mdi:price-tag',
            'pricing' => 'mdi:format-list-bulleted-square',
            'privacy' => 'mdi:shield-lock-outline',
            'procedure' => 'mdi:clipboard-check-outline',
            'processor' => 'mdi:cpu-64-bit',
            'product' => 'mdi:package-variant',
            'productline' => 'mdi:package-variant-closed',
            'profile' => 'mdi:account-box',
            'program' => 'mdi:school-outline',
            'project' => 'mdi:folder-star',
            'promotion' => 'mdi:arrow-up-bold',
            'property' => 'mdi:home-city',
            'proposal' => 'mdi:file-document-box',
            'provider' => 'mdi:domain',
            'publish' => 'mdi:send',
            'purchase' => 'mdi:cart',
            'qualification' => 'mdi:certificate-outline',
            'queue' => 'mdi:format-list-bulleted',
            'quote' => 'mdi:format-quote-close',
            'radio' => 'mdi:radio',
            'radiobutton' => 'mdi:radiobox-marked',
            'range' => 'mdi:ray-start-end',
            'rate' => 'mdi:star-rate',
            'reaction' => 'mdi:emoticon',
            'receipt' => 'mdi:receipt',
            'reconcile' => 'mdi:bank-check',
            'record' => 'mdi:record',
            'recovery' => 'mdi:refresh-circle',
            'redirect' => 'mdi:repeat',
            'redirected' => 'mdi:link-box',
            'refresh' => 'mdi:refresh',
            'refund' => 'mdi:cash-refund',
            'release' => 'mdi:tag-outline',
            'remote' => 'mdi:remote',
            'repair' => 'mdi:tools-wrench',
            'report' => 'mdi:chart-box',
            'request' => 'mdi:send',
            'requester' => 'mdi:account-arrow-right',
            'research' => 'mdi:magnify',
            'reservation' => 'mdi:calendar-clock',
            'resource' => 'mdi:database-outline',
            'response' => 'mdi:reply',
            'review' => 'mdi:eye-check-outline',
            'revision' => 'mdi:file-document-box-multiple-outline',
            'ride' => 'mdi:bike',
            'rights' => 'mdi:shield-account',
            'role' => 'mdi:account-badge',
            'route' => 'mdi:route',
            'routing' => 'mdi:router-wireless',
            'sale' => 'mdi:cash-multiple',
            'salesforce' => 'mdi:cloud',
            'scale' => 'mdi:scale-balance',
            'schedule' => 'mdi:calendar-clock',
            'schema' => 'mdi:schema',
            'screen' => 'mdi:monitor',
            'search' => 'mdi:magnify',
            'secure' => 'mdi:shield-check',
            'security' => 'mdi:shield-lock',
            'securitygroup' => 'mdi:shield-group',
            'segment' => 'mdi:shape',
            'seller' => 'mdi:store',
            'service' => 'mdi:tools',
            'servicelevel' => 'mdi:star-circle-outline',
            'session' => 'mdi:clock-outline',
            'sessiontoken' => 'mdi:key-outline',
            'settings' => 'mdi:cog',
            'setup' => 'mdi:hammer-wrench',
            'share' => 'mdi:share-variant',
            'shipment' => 'mdi:truck',
            'shortcode' => 'mdi:code-tags',
            'sidebar' => 'mdi:view-sidebar',
            'signature' => 'mdi:signature',
            'site' => 'mdi:web',
            'sitemap' => 'mdi:sitemap',
            'skill' => 'mdi:brain',
            'sms' => 'mdi:message-text-outline',
            'snapshot' => 'mdi:camera-flip',
            'social' => 'mdi:share-circle',
            'source' => 'mdi:source-branch',
            'spam' => 'mdi:spam',
            'sponsor' => 'mdi:heart-circle',
            'sprint' => 'mdi:run-fast',
            'stage' => 'mdi:stage',
            'stakeholder' => 'mdi:account-group-outline',
            'stamp' => 'mdi:stamp',
            'standard' => 'mdi:check-bold',
            'startup' => 'mdi:rocket-launch',
            'state' => 'mdi:map-marker',
            'statement' => 'mdi:note',
            'status' => 'mdi:check-circle',
            'stock' => 'mdi:warehouse',
            'story' => 'mdi:book',
            'strategy' => 'mdi:chess-king',
            'stream' => 'mdi:playlist-play',
            'structure' => 'mdi:architecture',
            'student' => 'mdi:school',
            'study' => 'mdi:mortar-board',
            'style' => 'mdi:format-paint',
            'subject' => 'mdi:book-open',
            'submission' => 'mdi:send-check',
            'subscription' => 'mdi:bell-ring',
            'subsystem' => 'mdi:cubes',
            'success' => 'mdi:check-circle',
            'summary' => 'mdi:format-list-bulleted',
            'supplier' => 'mdi:truck-delivery',
            'support' => 'mdi:lifebuoy',
            'survey' => 'mdi:clipboard-list',
            'sync' => 'mdi:sync',
            'system' => 'mdi:desktop-tower',
            'tactic' => 'mdi:target',
            'tag' => 'mdi:tag-multiple',
            'task' => 'mdi:checkbox-marked',
            'tasklist' => 'mdi:format-list-checkbox',
            'team' => 'mdi:account-group',
            'teammember' => 'mdi:account-multiple-check',
            'template' => 'mdi:table',
            'templateitem' => 'mdi:table',
            'tender' => 'mdi:handshake',
            'term' => 'mdi:file-document-outline',
            'territory' => 'mdi:map-marker',
            'test' => 'mdi:check-all',
            'ticket' => 'mdi:ticket',
            'ticketing' => 'mdi:ticket-confirmation',
            'time' => 'mdi:clock-time-four',
            'timezone' => 'mdi:clock-time-four-outline',
            'toast' => 'mdi:bell-outline',
            'token' => 'mdi:key-star',
            'tokenization' => 'mdi:key-plus',
            'tool' => 'mdi:wrench',
            'topic' => 'mdi:forum',
            'trade' => 'mdi:swap-horizontal-bold',
            'transaction' => 'mdi:swap-horizontal',
            'travel' => 'mdi:airplane',
            'tree' => 'mdi:tree',
            'trend' => 'mdi:trending-up',
            'trip' => 'mdi:map-marker-path',
            'trophy' => 'mdi:trophy',
            'trust' => 'mdi:shield-check',
            'type' => 'mdi:shape',
            'typeahead' => 'mdi:search-web',
            'typography' => 'mdi:format-font',
            'ui' => 'mdi:monitor-dashboard',
            'uicomponent' => 'mdi:vector-square',
            'ultimate' => 'mdi:crown',
            'uncategorized' => 'mdi:tag-off',
            'underwriting' => 'mdi:shield-check-outline',
            'uniform' => 'mdi:tshirt-crew',
            'unlock' => 'mdi:lock-open',
            'update' => 'mdi:update',
            'upload' => 'mdi:upload',
            'uploadhistory' => 'mdi:upload',
            'user' => 'mdi:account',
            'usergroup' => 'mdi:account-group',
            'utility' => 'mdi:wrench',
            'vacation' => 'mdi:beach',
            'validation' => 'mdi:check-decagram',
            'validationrule' => 'mdi:check-decagram',
            'value' => 'mdi:currency-usd-circle',
            'valueobject' => 'mdi:hexagon-multiple',
            'vendor' => 'mdi:store',
            'vendoraccount' => 'mdi:store-check',
            'version' => 'mdi:tag-text-outline',
            'versioncontrol' => 'mdi:source-branch',
            'video' => 'mdi:video',
            'videocall' => 'mdi:video-plus',
            'view' => 'mdi:eye',
            'viewmode' => 'mdi:eye-outline',
            'virtual' => 'mdi:cloud',
            'visitor' => 'mdi:account-eye',
            'voice' => 'mdi:record-rec',
            'volume' => 'mdi:volume-high',
            'voucher' => 'mdi:ticket-percent',
            'wallet' => 'mdi:wallet',
            'warning' => 'mdi:alert',
            'warningtriangle' => 'mdi:alert-outline',
            'warranty' => 'mdi:shield-check',
            'watch' => 'mdi:watch',
            'watermark' => 'mdi:watermark',
            'web' => 'mdi:web',
            'webhook' => 'mdi:webhook',
            'webshop' => 'mdi:cart',
            'website' => 'mdi:web',
            'week' => 'mdi:calendar-week',
            'weight' => 'mdi:scale-balance',
            'wheel' => 'mdi:wheelchair',
            'whitepaper' => 'mdi:file-pdf-box',
            'widget' => 'mdi:widgets',
            'widgetarea' => 'mdi:widgets',
            'wifi' => 'mdi:wifi',
            'workflow' => 'mdi:progress-clock',
            'workflowengine' => 'mdi:progress-check',
            'year' => 'mdi:calendar',
            'yield' => 'mdi:trending-up',
            'zip' => 'mdi:archive-arrow-down',
            'zone' => 'mdi:map-marker-multiple',
            'zoom' => 'mdi:magnify-plus',
        ];

        foreach ($map as $keyword => $icon) {
            if (str_contains(strtolower($shortName), $keyword)) {
                return $icon;
            }
        }

        // Generic fallbacks based on naming
        return match (true) {
            str_ends_with($shortName, 'Repository') => 'mdi:database',
            str_ends_with($shortName, 'Controller') => 'mdi:controller',
            str_ends_with($shortName, 'Form') => 'mdi:form-select',
            str_ends_with($shortName, 'Dto') => 'mdi:code-braces',
            str_ends_with($shortName, 'Event') => 'mdi:calendar-star',
            default => $this->fallback($className, 'mdi:file'),
        };
    }

    /**
     * @param ReflectionClass<object>|string $className
     */
    private function fallback(ReflectionClass|string $className, string $fallbackIcon): string
    {
        $suffix = is_string($className) ? KebabCaseSlug::fromText($className) : KebabCaseSlug::fromClass($className);
        if ($this->iconRegistry) {
            try {
                $this->iconRegistry->get('mdi:' . $suffix);

                return 'mdi:' . $suffix;
            } catch (IconNotFoundException) {
            }
        }
        return $fallbackIcon;
    }
}
